name: weather_app
description: "Clean Arch & Testing"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.5
  get_it: ^7.6.7
  http: ^1.2.0
  rxdart: ^0.27.7
  dartz: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  bloc_test: ^9.1.7
  mockito: ^5.4.4
  mocktail: ^1.0.3

flutter:

  uses-material-design: true
